#
# regression test 3 
#
#   test basic inclusion mechanism
#  
#   note that file $[1] is filled in by the reg-tester, and resovles
#   to whatever the file is (as generated by the regtest harness)
#
#-----------------------------------------------------------------------

dct = { "v" : "var v",
        "js" : 'javascript:$("foo").bar' }

parent1 = """ {$ include ("$[1]", %s) $} """  % dct
parent2 = """ 
{$ locals { file : "$[1]" } $}
{$ include (file, %s) $}
""" % dct

child = """
${v}
${js}
""" 

outcome ="""
%s
%s
""" % (dct["v"],
       dct["js"])

cases = [ { "filedata" : [ parent1, child ],
            "outcome" : outcome,
            "desc" : "straight-ahead file inclusion" },
          { "filedata" : [ parent2, child ],
            "outcome" : outcome,
            "desc" : "inclusion via filename expansion" } ]

