#!/bin/sh

CFG=cfg

if [ -f $CFG ]
then
    rm $CFG
fi

touch $CFG
if [ $DEBUG ]
then
    echo "export DEBUG=$DEBUG" > $CFG
fi
CONFIGURE=`echo $0 | sed 's/cfg/configure/' `
echo "$CONFIGURE $*" >> $CFG
chmod u+x $CFG
sh -x $CFG
