
CREATE TABLE IF NOT EXISTS tst2 (
       id    INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       s     VARCHAR(255) NOT NULL,
       d     DATETIME NOT NULL,
       i     INTEGER UNSIGNED NOT NULL,
       d2    DATE NOT NULL,
       UNIQUE INDEX key_index (s)
);
